thermo_microscope: #this is where you would define new machines to load
#and we also need to define the servers for each piece of equipmen
  - name: REAL STEMMicroscope
    value: real
  - name: Digital Twin
    value: dt
base_microscope: 
  - name: Base
    value: base